name: .NET Tests Workflow

on:
  push:
    branches:
      - main  # Der Workflow wird bei Pushes auf den main-Branch ausgeführt
  pull_request:
    branches:
      - main  # Der Workflow wird bei Pull-Requests auf den main-Branch ausgeführt

jobs:
  build:
    runs-on: windows-latest  # Der Workflow wird auf einer Windows-Maschine ausgeführt

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Holt das Repository

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Gibt die .NET Version an (wähle die Version, die du verwendest)

      - name: Restore dependencies
        run: dotnet restore  # Stellt die Abhängigkeiten des Projekts wieder her

      - name: Build the project
        run: dotnet build --configuration Release  # Baut das Projekt im Release-Modus

      - name: Run tests
        run: dotnet test --configuration Release  # Führt die Unit Tests aus

      # Der Schritt zum Veröffentlichen der Testergebnisse wurde entfernt
